version: '2.4'
services:

    # ---------------------------------
    # TRAEFIK
    # ---------------------------------
    traefik:
        image: traefik:2.4
        volumes:
          - ./traefik/traefik.yml:/etc/traefik/traefik.yml
          - /var/run/docker.sock:/var/run/docker.sock
        links:
          - server
        ports:
         - "3000:80"
         - "127.0.0.1:8080:8080"

    # ---------------------------------
    # DB
    # ---------------------------------
    mariadb:
      container_name: mariadb
      image: mariadb:10.5.9
      hostname: mariadb
      command: [
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
      ]
      restart: always
      environment:
        MYSQL_DATABASE: ${DB_NAME:-database}
        MYSQL_USER: ${DB_USER:-user}
        MYSQL_PASSWORD: ${DB_PASSWORD:-user}
        MYSQL_ROOT_PASSWORD:  ${DB_ROOT_PASSWORD:-user}
      volumes:
        - vol-db-data:/var/lib/mysql
      ports:
        - '127.0.0.1:3306:3306'
      labels:
        - traefik.enable=false
      healthcheck:
        test: "/usr/bin/mysql --user=${DB_USER:-user} --password=${DB_PASS:-user} --execute \"SHOW DATABASES;\""
        interval: 3s
        timeout: 1s
        retries: 5
      

    # ---------------------------------
    # SERVER
    # ---------------------------------
    server:
      hostname: server
      build: .
      restart: always
      user: '${USER_ID}:${GROUP_ID}'
      links:
        - mariadb
      labels:
        - "traefik.http.routers.${NAME:-app}.rule=PathPrefix(`/`)"
        - traefik.http.services.${NAME:-app}.loadBalancer.sticky.cookie.name=server_id
        - traefik.http.services.${NAME:-app}.loadBalancer.sticky.cookie.httpOnly=true
      volumes:
        - vol-server-data:/usr/src/app/static
        - ./app:/app/web
      depends_on:
        maria-db:
        condition: service_healthy

    # ---------------------------------
    # Tools dev or integration
    # ---------------------------------
    mysql-admin:
      container_name: mysql-admin
      hostname: mysql-admin
      image: phpmyadmin/phpmyadmin:5.1.0
      environment:
        PMA_HOST: mariadb
        PMA_PORT: 3306
        MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-user}
        PMA_USER: ${DB_USER:-user}
        PMA_PASSWORD: ${DB_PASSWORD:-user}
      ports:
        - '127.0.0.1:3380:80'
      restart: always
      depends_on:
        maria-db:
        condition: service_healthy
        
    adminer:
      image: adminer
      environment:
        ADMINER_DESIGN: pepa-linha
        ADMINER_DEFAULT_SERVER: mariadb
      ports:
        - 8888:8080
        
    mail:
      image: mailhog/mailhog
      ports:
        - 1080:8025
        
volumes:
  vol-db-data:
    driver: local
  vol-server-data:
    driver: local
