version: '2.4'
services:

    # ---------------------------------
    # TRAEFIK
    # ---------------------------------
    traefik:
        image: traefik:2.4
        volumes:
          - ./traefik/traefik.yml:/etc/traefik/traefik.yml
          - /var/run/docker.sock:/var/run/docker.sock
        links:
          - server
        ports:
         - "3000:80"
         - "127.0.0.1:8080:8080"

    # ---------------------------------
    # DB
    # ---------------------------------
    db:
      container_name: db
      image: mysql:8.0.19
      hostname: db
      command: [
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
      ]
      restart: always
      environment:
        MYSQL_DATABASE: ${DB_NAME:-database}
        MYSQL_USER: ${DB_USER:-user}
        MYSQL_PASSWORD: ${DB_PASSWORD:-user}
        MYSQL_ROOT_PASSWORD:  ${DB_ROOT_PASSWORD:-user}
      volumes:
        - vol-db-data:/var/lib/mysql
      ports:
        - '127.0.0.1:3306:3306'
      labels:
        - traefik.enable=false
      
    # ---------------------------------
    # SERVER
    # ---------------------------------
    server:
      hostname: server
      build: .
      restart: always
      user: '${USER_ID}:${GROUP_ID}'
      links:
        - db
      labels:
        - "traefik.http.routers.${NAME:-app}.rule=PathPrefix(`/`)"
        - traefik.http.services.${NAME:-app}.loadBalancer.sticky.cookie.name=server_id
        - traefik.http.services.${NAME:-app}.loadBalancer.sticky.cookie.httpOnly=true
      volumes:
        - ./app:/app/web
      extra_hosts:
        - host.docker.internal:host-gateway


    # ---------------------------------
    # Tools dev or integration
    # ---------------------------------
    adminer:
      image: adminer
      environment:
        ADMINER_DESIGN: pepa-linha
        ADMINER_DEFAULT_SERVER: db
      ports:
        - 8888:8080
        
    mail:
      image: mailhog/mailhog
      ports:
        - 1080:8025
        
volumes:
  vol-db-data:
    driver: local
